"""empty message

Revision ID: 141ca32943a7
Revises: 5ed542a75e2a
Create Date: 2022-12-12 13:56:33.350908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141ca32943a7'
down_revision = '5ed542a75e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.drop_constraint('car_car_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])
        batch_op.drop_column('car_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('car_car_token_fkey', 'user', ['car_token'], ['token'])
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
